# Generated by Django 5.2.8 on 2026-01-30 07:45

import creator_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='portfolio_uploads',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='portfolio_uploads',
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('collaborator', 'Collaborator')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('media_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=creator_app.models.portfolio_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='creator_app.userdata')),
            ],
        ),
    ]
