# Generated by Django 5.2.8 on 2026-02-16 11:09

import creator_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0002_remove_collaboratorprofile_portfolio_uploads_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='title',
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='collaboration_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='portfolio_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of display'),
        ),
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_profile', to='creator_app.userdata'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=creator_app.models.portfolio_upload_path),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('collaborator', 'Collaborator')], default='creator', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='creator_app.userdata'),
        ),
    ]
